
var YaneuraOu_K_P = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(moduleArg = {}) {

function d(){h.buffer!=q.buffer&&t();return q}function aa(){h.buffer!=q.buffer&&t();return ba}function ca(){h.buffer!=q.buffer&&t();return da}function v(){h.buffer!=q.buffer&&t();return ea}function x(){h.buffer!=q.buffer&&t();return fa}function ha(){h.buffer!=q.buffer&&t();return ia}var z=moduleArg,ja,ka;z.ready=new Promise((a,b)=>{ja=a;ka=b});
(function(){function a(){var g=e.shift();if(!b&&void 0!==g){if("quit"===g)return z.terminate();var k=z.ccall("usi_command","number",["string"],[g]);k&&e.unshift(g);f=k?2*f:1;setTimeout(a,f)}}var b=!1,c=[];z.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var k=0;k<c.length;k++)c[k](g)})};z.addMessageListener=function(g){c.push(g)};z.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};z.terminate=function(){b=!0;B.Qb()};var e=[],f=1;z.postMessage=function(g){e.push(g)};
z.postRun=function(){z.postMessage=function(g){e.push(g);1===e.length&&a()};a()}})();var la=Object.assign({},z),ma=[],na="./this.program",oa=(a,b)=>{throw b;},pa="object"==typeof window,E="function"==typeof importScripts,qa="object"==typeof process&&"object"==typeof process.Qc&&"string"==typeof process.Qc.node,F=z.ENVIRONMENT_IS_PTHREAD||!1,G="";function ra(a){return z.locateFile?z.locateFile(a,G):G+a}var sa,ta,ua;
if(pa||E)E?G=self.location.href:"undefined"!=typeof document&&document.currentScript&&(G=document.currentScript.src),_scriptDir&&(G=_scriptDir),0!==G.indexOf("blob:")?G=G.substr(0,G.replace(/[?#].*/,"").lastIndexOf("/")+1):G="",sa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},E&&(ua=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ta=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,
!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var va=z.print||console.log.bind(console),H=z.printErr||console.error.bind(console);Object.assign(z,la);la=null;z.arguments&&(ma=z.arguments);z.thisProgram&&(na=z.thisProgram);z.quit&&(oa=z.quit);var I;z.wasmBinary&&(I=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!=typeof WebAssembly&&J("no native wasm support detected");var h,wa,xa=!1,L,q,ba,da,ea,fa,ia;
function t(){var a=h.buffer;z.HEAP8=q=new Int8Array(a);z.HEAP16=da=new Int16Array(a);z.HEAP32=ea=new Int32Array(a);z.HEAPU8=ba=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAPU32=fa=new Uint32Array(a);z.HEAPF32=new Float32Array(a);z.HEAPF64=ia=new Float64Array(a)}var ya=z.INITIAL_MEMORY||92274688;67108864<=ya||J("INITIAL_MEMORY should be larger than STACK_SIZE, was "+ya+"! (STACK_SIZE=67108864)");
if(F)h=z.wasmMemory;else if(z.wasmMemory)h=z.wasmMemory;else if(h=new WebAssembly.Memory({initial:ya/65536,maximum:65536,shared:!0}),!(h.buffer instanceof SharedArrayBuffer))throw H("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),qa&&H("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");t();ya=h.buffer.byteLength;var za,Aa=[],Ba=[],Ca=[],Da=[],Ea=0;function Fa(){return noExitRuntime||0<Ea}function Ga(){F||(z.noFSInit||M.va.kb||M.va(),M.Lb=!1,Ha(Ba))}var N=0,Ia=null,O=null;function Ja(){N++;z.monitorRunDependencies&&z.monitorRunDependencies(N)}function P(){N--;z.monitorRunDependencies&&z.monitorRunDependencies(N);if(0==N&&(null!==Ia&&(clearInterval(Ia),Ia=null),O)){var a=O;O=null;a()}}
function J(a){if(z.onAbort)z.onAbort(a);a="Aborted("+a+")";H(a);xa=!0;L=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ka(a);throw a;}function Ka(a){return a.startsWith("data:application/octet-stream;base64,")}var Q;z.locateFile?(Q="yaneuraou.k-p.wasm",Ka(Q)||(Q=ra(Q))):Q=(new URL("yaneuraou.k-p.wasm",import.meta.url)).href;function La(a){if(a==Q&&I)return new Uint8Array(I);if(ua)return ua(a);throw"both async and sync fetching of the wasm failed";}
function Ma(a){return I||!pa&&!E||"function"!=typeof fetch?Promise.resolve().then(()=>La(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>La(a))}function Na(a,b,c){return Ma(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(c,e=>{H("failed to asynchronously prepare wasm: "+e);J(e)})}
function Oa(a,b){var c=Q;return I||"function"!=typeof WebAssembly.instantiateStreaming||Ka(c)||"function"!=typeof fetch?Na(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){H("wasm streaming compile failed: "+f);H("falling back to ArrayBuffer instantiation");return Na(c,a,b)}))}var R,Pa;function Qa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}function Ra(a){a.terminate();a.onmessage=()=>{}}
function Sa(a){(a=B.qa[a])||J();B.Gc(a)}function Ta(a){var b=B.nc();if(!b)return 6;B.Da.push(b);B.qa[a.Ba]=b;b.Ba=a.Ba;b.postMessage({cmd:"run",start_routine:a.Ic,arg:a.Zb,pthread_ptr:a.Ba},a.Oc);return 0}
var Ua=(a,b)=>{for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},S=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ua(a.split("/").filter(e=>!!e),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Va=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},T=a=>{if("/"===
a)return"/";a=S(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=(a,b)=>S(a+"/"+b),Xa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),a);J("initRandomDevice")},Ya=a=>(Ya=Xa())(a);
function U(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:M.Ua();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ua(a.split("/").filter(e=>!!e),!b).join("/");return(b?"/":"")+a||"."}
var Za=(a,b)=>{function c(k){for(var n=0;n<k.length&&""===k[n];n++);for(var u=k.length-1;0<=u&&""===k[u];u--);return n>u?[]:k.slice(n,u-n+1)}a=U(a).substr(1);b=U(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")},$a="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,V=(a,b)=>{b>>>=0;for(var c=b+NaN,e=b;a[e]&&!(e>=c);)++e;if(16<
e-b&&a.buffer&&$a)return $a.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,e):a.subarray(b,e));for(c="";b<e;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},ab=[],bb=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=
e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},cb=(a,b,c,e)=>{c>>>=0;if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=e)break;b[c++>>>0]=k}else{if(2047>=k){if(c+1>=e)break;b[c++>>>0]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++>>>0]=224|k>>12}else{if(c+3>=e)break;b[c++>>>0]=240|k>>18;b[c++>>>0]=128|k>>12&63}b[c++>>>0]=128|k>>6&63}b[c++>>>0]=128|k&63}}b[c>>>
0]=0;return c-f};function db(a,b){var c=Array(bb(a)+1);a=cb(a,c,0,c.length);b&&(c.length=a);return c}var eb=[];function fb(a,b){eb[a]={input:[],ca:[],pa:b};M.tb(a,gb)}
var gb={open:function(a){var b=eb[a.node.$a];if(!b)throw new M.T(43);a.X=b;a.seekable=!1},close:function(a){a.X.pa.Va(a.X)},Va:function(a){a.X.pa.Va(a.X)},read:function(a,b,c,e){if(!a.X||!a.X.pa.Hb)throw new M.T(60);for(var f=0,g=0;g<e;g++){try{var k=a.X.pa.Hb(a.X)}catch(n){throw new M.T(29);}if(void 0===k&&0===f)throw new M.T(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){if(!a.X||!a.X.pa.qb)throw new M.T(60);try{for(var f=0;f<e;f++)a.X.pa.qb(a.X,
b[c+f])}catch(g){throw new M.T(29);}e&&(a.node.timestamp=Date.now());return f}},hb={Hb:function(){a:{if(!ab.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}ab=db(a,!0)}a=ab.shift()}return a},qb:function(a,b){null===b||10===b?(va(V(a.ca,0)),a.ca=[]):0!=b&&a.ca.push(b)},Va:function(a){a.ca&&0<a.ca.length&&(va(V(a.ca,0)),a.ca=[])},rc:function(){return{Xc:25856,
Zc:5,Wc:191,Yc:35387,Vc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},sc:function(){return 0},tc:function(){return[24,80]}},ib={qb:function(a,b){null===b||10===b?(H(V(a.ca,0)),a.ca=[]):0!=b&&a.ca.push(b)},Va:function(a){a.ca&&0<a.ca.length&&(H(V(a.ca,0)),a.ca=[])}};function jb(a,b){var c=a.V?a.V.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.V,a.V=new Uint8Array(b),0<a.Z&&a.V.set(c.subarray(0,a.Z),0))}
var W={ka:null,$(){return W.createNode(null,"/",16895,0)},createNode(a,b,c,e){if(M.uc(c)||M.vc(c))throw new M.T(63);W.ka||(W.ka={dir:{node:{ha:W.U.ha,ba:W.U.ba,xa:W.U.xa,oa:W.U.oa,Pa:W.U.Pa,Ra:W.U.Ra,Qa:W.U.Qa,Oa:W.U.Oa,sa:W.U.sa},stream:{ia:W.W.ia}},file:{node:{ha:W.U.ha,ba:W.U.ba},stream:{ia:W.W.ia,read:W.W.read,write:W.W.write,Ha:W.W.Ha,Ga:W.W.Ga,Na:W.W.Na}},link:{node:{ha:W.U.ha,ba:W.U.ba,Ca:W.U.Ca},stream:{}},yb:{node:{ha:W.U.ha,ba:W.U.ba},stream:M.bc}});c=M.createNode(a,b,c,e);M.aa(c.mode)?
(c.U=W.ka.dir.node,c.W=W.ka.dir.stream,c.V={}):M.isFile(c.mode)?(c.U=W.ka.file.node,c.W=W.ka.file.stream,c.Z=0,c.V=null):M.Ka(c.mode)?(c.U=W.ka.link.node,c.W=W.ka.link.stream):M.Wa(c.mode)&&(c.U=W.ka.yb.node,c.W=W.ka.yb.stream);c.timestamp=Date.now();a&&(a.V[b]=c,a.timestamp=c.timestamp);return c},md(a){return a.V?a.V.subarray?a.V.subarray(0,a.Z):new Uint8Array(a.V):new Uint8Array(0)},U:{ha(a){var b={};b.gd=M.Wa(a.mode)?a.id:1;b.od=a.id;b.mode=a.mode;b.xd=1;b.uid=0;b.nd=0;b.$a=a.$a;M.aa(a.mode)?b.size=
4096:M.isFile(a.mode)?b.size=a.Z:M.Ka(a.mode)?b.size=a.link.length:b.size=0;b.Tc=new Date(a.timestamp);b.vd=new Date(a.timestamp);b.ed=new Date(a.timestamp);b.$b=4096;b.Uc=Math.ceil(b.size/b.$b);return b},ba(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Z!=b))if(0==b)a.V=null,a.Z=0;else{var c=a.V;a.V=new Uint8Array(b);c&&a.V.set(c.subarray(0,Math.min(b,a.Z)));a.Z=b}},xa(){throw M.hb[44];},oa(a,b,c,e){return W.createNode(a,b,c,
e)},Pa(a,b,c){if(M.aa(a.mode)){try{var e=M.na(b,c)}catch(g){}if(e)for(var f in e.V)throw new M.T(55);}delete a.parent.V[a.name];a.parent.timestamp=Date.now();a.name=c;b.V[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Ra(a,b){delete a.V[b];a.timestamp=Date.now()},Qa(a,b){var c=M.na(a,b),e;for(e in c.V)throw new M.T(55);delete a.V[b];a.timestamp=Date.now()},Oa(a){var b=[".",".."],c;for(c in a.V)a.V.hasOwnProperty(c)&&b.push(c);return b},sa(a,b,c){a=W.createNode(a,b,41471,0);a.link=c;return a},Ca(a){if(!M.Ka(a.mode))throw new M.T(28);
return a.link}},W:{read(a,b,c,e,f){var g=a.node.V;if(f>=a.node.Z)return 0;a=Math.min(a.node.Z-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write(a,b,c,e,f,g){b.buffer===d().buffer&&(g=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.V||a.V.subarray)){if(g)return a.V=b.subarray(c,c+e),a.Z=e;if(0===a.Z&&0===f)return a.V=b.slice(c,c+e),a.Z=e;if(f+e<=a.Z)return a.V.set(b.subarray(c,c+e),f),e}jb(a,f+e);if(a.V.subarray&&b.subarray)a.V.set(b.subarray(c,
c+e),f);else for(g=0;g<e;g++)a.V[f+g]=b[c+g];a.Z=Math.max(a.Z,f+e);return e},ia(a,b,c){1===c?b+=a.position:2===c&&M.isFile(a.node.mode)&&(b+=a.node.Z);if(0>b)throw new M.T(28);return b},Ha(a,b,c){jb(a.node,b+c);a.node.Z=Math.max(a.node.Z,b+c)},Ga(a,b,c,e,f){if(!M.isFile(a.node.mode))throw new M.T(43);a=a.node.V;if(f&2||a.buffer!==d().buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;J();b=void 0;if(!b)throw new M.T(48);d().set(a,b>>>0)}else c=!1,
b=a.byteOffset;return{zd:b,Sc:c}},Na(a,b,c,e){W.W.write(a,b,0,e,c,!1);return 0}}},kb=(a,b,c)=>{var e=`al ${a}`;ta(a,f=>{f||J(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(f));e&&P()},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});e&&Ja()},lb=z.preloadPlugins||[];function mb(a,b,c,e){"undefined"!=typeof Browser&&Browser.va();var f=!1;lb.forEach(function(g){!f&&g.canHandle(b)&&(g.handle(a,b,c,e),f=!0)});return f}
function nb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var M={root:null,Ma:[],Cb:{},streams:[],Ac:1,ja:null,Bb:"/",kb:!1,Lb:!0,T:null,hb:{},lc:null,ab:0,Y:(a,b={})=>{a=U(a);if(!a)return{path:"",node:null};b=Object.assign({fb:!0,sb:0},b);if(8<b.sb)throw new M.T(32);a=a.split("/").filter(k=>!!k);for(var c=M.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=M.na(c,a[f]);e=S(e+"/"+a[f]);M.wa(c)&&(!g||g&&b.fb)&&(c=c.La.root);if(!g||b.ga)for(g=0;M.Ka(c.mode);)if(c=M.Ca(e),e=U(Va(e),c),c=M.Y(e,{sb:b.sb+1}).node,40<g++)throw new M.T(32);
}return{path:e,node:c}},ua:a=>{for(var b;;){if(M.Xa(a))return a=a.$.Nb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},jb:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%M.ja.length},Jb:a=>{var b=M.jb(a.parent.id,a.name);a.za=M.ja[b];M.ja[b]=a},Kb:a=>{var b=M.jb(a.parent.id,a.name);if(M.ja[b]===a)M.ja[b]=a.za;else for(b=M.ja[b];b;){if(b.za===a){b.za=a.za;break}b=b.za}},na:(a,b)=>{var c=M.yc(a);if(c)throw new M.T(c,a);for(c=M.ja[M.jb(a.id,
b)];c;c=c.za){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return M.xa(a,b)},createNode:(a,b,c,e)=>{a=new M.Tb(a,b,c,e);M.Jb(a);return a},eb:a=>{M.Kb(a)},Xa:a=>a===a.parent,wa:a=>!!a.La,isFile:a=>32768===(a&61440),aa:a=>16384===(a&61440),Ka:a=>40960===(a&61440),Wa:a=>8192===(a&61440),uc:a=>24576===(a&61440),vc:a=>4096===(a&61440),pd:a=>49152===(a&49152),Fb:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Aa:(a,b)=>{if(M.Lb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&
!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},yc:a=>{var b=M.Aa(a,"x");return b?b:a.U.xa?0:2},pb:(a,b)=>{try{return M.na(a,b),20}catch(c){}return M.Aa(a,"wx")},Ya:(a,b,c)=>{try{var e=M.na(a,b)}catch(f){return f.da}if(a=M.Aa(a,"wx"))return a;if(c){if(!M.aa(e.mode))return 54;if(M.Xa(e)||M.ua(e)===M.Ua())return 10}else if(M.aa(e.mode))return 31;return 0},zc:(a,b)=>a?M.Ka(a.mode)?32:M.aa(a.mode)&&("r"!==M.Fb(b)||b&512)?31:M.Aa(a,M.Fb(b)):44,Ub:4096,Bc:()=>{for(var a=0;a<=
M.Ub;a++)if(!M.streams[a])return a;throw new M.T(33);},ea:a=>{a=M.oc(a);if(!a)throw new M.T(8);return a},oc:a=>M.streams[a],Ab:(a,b=-1)=>{M.Sa||(M.Sa=function(){this.ma={}},M.Sa.prototype={},Object.defineProperties(M.Sa.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ma.flags},set(c){this.ma.flags=c}},position:{get(){return this.ma.position},set(c){this.ma.position=c}}}));a=Object.assign(new M.Sa,a);-1==b&&(b=M.Bc());a.Ia=b;return M.streams[b]=a},cc:a=>{M.streams[a]=
null},bc:{open:a=>{a.W=M.mc(a.node.$a).W;a.W.open&&a.W.open(a)},ia:()=>{throw new M.T(70);}},ob:a=>a>>8,td:a=>a&255,ya:(a,b)=>a<<8|b,tb:(a,b)=>{M.Cb[a]={W:b}},mc:a=>M.Cb[a],Gb:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Ma)}return b},Pb:(a,b)=>{function c(k){M.ab--;return b(k)}function e(k){if(k){if(!e.kc)return e.kc=!0,c(k)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);M.ab++;1<M.ab&&H(`warning: ${M.ab} FS.syncfs operations in flight at once, probably just doing extra work`);
var f=M.Gb(M.root.$),g=0;f.forEach(k=>{if(!k.type.Pb)return e(null);k.type.Pb(k,a,e)})},$:(a,b,c)=>{var e="/"===c,f=!c;if(e&&M.root)throw new M.T(10);if(!e&&!f){var g=M.Y(c,{fb:!1});c=g.path;g=g.node;if(M.wa(g))throw new M.T(10);if(!M.aa(g.mode))throw new M.T(54);}b={type:a,yd:b,Nb:c,Ma:[]};a=a.$(b);a.$=b;b.root=a;e?M.root=a:g&&(g.La=b,g.$&&g.$.Ma.push(b));return a},Fd:a=>{a=M.Y(a,{fb:!1});if(!M.wa(a.node))throw new M.T(28);a=a.node;var b=a.La,c=M.Gb(b);Object.keys(M.ja).forEach(e=>{for(e=M.ja[e];e;){var f=
e.za;c.includes(e.$)&&M.eb(e);e=f}});a.La=null;a.$.Ma.splice(a.$.Ma.indexOf(b),1)},xa:(a,b)=>a.U.xa(a,b),oa:(a,b,c)=>{var e=M.Y(a,{parent:!0}).node;a=T(a);if(!a||"."===a||".."===a)throw new M.T(28);var f=M.pb(e,a);if(f)throw new M.T(f);if(!e.U.oa)throw new M.T(63);return e.U.oa(e,a,b,c)},create:(a,b)=>M.oa(a,(void 0!==b?b:438)&4095|32768,0),fa:(a,b)=>M.oa(a,(void 0!==b?b:511)&1023|16384,0),ud:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{M.fa(c,b)}catch(f){if(20!=
f.da)throw f;}}},Za:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return M.oa(a,b|8192,c)},sa:(a,b)=>{if(!U(a))throw new M.T(44);var c=M.Y(b,{parent:!0}).node;if(!c)throw new M.T(44);b=T(b);var e=M.pb(c,b);if(e)throw new M.T(e);if(!c.U.sa)throw new M.T(63);return c.U.sa(c,b,a)},Pa:(a,b)=>{var c=Va(a),e=Va(b),f=T(a),g=T(b);var k=M.Y(a,{parent:!0});var n=k.node;k=M.Y(b,{parent:!0});k=k.node;if(!n||!k)throw new M.T(44);if(n.$!==k.$)throw new M.T(75);var u=M.na(n,f);a=Za(a,e);if("."!==a.charAt(0))throw new M.T(28);
a=Za(b,c);if("."!==a.charAt(0))throw new M.T(55);try{var m=M.na(k,g)}catch(p){}if(u!==m){b=M.aa(u.mode);if(f=M.Ya(n,f,b))throw new M.T(f);if(f=m?M.Ya(k,g,b):M.pb(k,g))throw new M.T(f);if(!n.U.Pa)throw new M.T(63);if(M.wa(u)||m&&M.wa(m))throw new M.T(10);if(k!==n&&(f=M.Aa(n,"w")))throw new M.T(f);M.Kb(u);try{n.U.Pa(u,k,g)}catch(p){throw p;}finally{M.Jb(u)}}},Qa:a=>{var b=M.Y(a,{parent:!0}).node;a=T(a);var c=M.na(b,a),e=M.Ya(b,a,!0);if(e)throw new M.T(e);if(!b.U.Qa)throw new M.T(63);if(M.wa(c))throw new M.T(10);
b.U.Qa(b,a);M.eb(c)},Oa:a=>{a=M.Y(a,{ga:!0}).node;if(!a.U.Oa)throw new M.T(54);return a.U.Oa(a)},Ra:a=>{var b=M.Y(a,{parent:!0}).node;if(!b)throw new M.T(44);a=T(a);var c=M.na(b,a),e=M.Ya(b,a,!1);if(e)throw new M.T(e);if(!b.U.Ra)throw new M.T(63);if(M.wa(c))throw new M.T(10);b.U.Ra(b,a);M.eb(c)},Ca:a=>{a=M.Y(a).node;if(!a)throw new M.T(44);if(!a.U.Ca)throw new M.T(28);return U(M.ua(a.parent),a.U.Ca(a))},stat:(a,b)=>{a=M.Y(a,{ga:!b}).node;if(!a)throw new M.T(44);if(!a.U.ha)throw new M.T(63);return a.U.ha(a)},
sd:a=>M.stat(a,!0),Ta:(a,b,c)=>{a="string"==typeof a?M.Y(a,{ga:!c}).node:a;if(!a.U.ba)throw new M.T(63);a.U.ba(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},qd:(a,b)=>{M.Ta(a,b,!0)},hd:(a,b)=>{a=M.ea(a);M.Ta(a.node,b)},xb:(a,b,c,e)=>{a="string"==typeof a?M.Y(a,{ga:!e}).node:a;if(!a.U.ba)throw new M.T(63);a.U.ba(a,{timestamp:Date.now()})},rd:(a,b,c)=>{M.xb(a,b,c,!0)},jd:(a,b,c)=>{a=M.ea(a);M.xb(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new M.T(28);a="string"==typeof a?M.Y(a,{ga:!0}).node:a;
if(!a.U.ba)throw new M.T(63);if(M.aa(a.mode))throw new M.T(31);if(!M.isFile(a.mode))throw new M.T(28);var c=M.Aa(a,"w");if(c)throw new M.T(c);a.U.ba(a,{size:b,timestamp:Date.now()})},ld:(a,b)=>{a=M.ea(a);if(0===(a.flags&2097155))throw new M.T(28);M.truncate(a.node,b)},Gd:(a,b,c)=>{a=M.Y(a,{ga:!0}).node;a.U.ba(a,{timestamp:Math.max(b,c)})},open:(a,b,c)=>{if(""===a)throw new M.T(44);if("string"==typeof b){var e={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof e)throw Error(`Unknown file open mode: ${b}`);
b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=S(a);try{f=M.Y(a,{ga:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new M.T(20);}else f=M.oa(a,c,0),e=!0;if(!f)throw new M.T(44);M.Wa(f.mode)&&(b&=-513);if(b&65536&&!M.aa(f.mode))throw new M.T(54);if(!e&&(c=M.zc(f,b)))throw new M.T(c);b&512&&!e&&M.truncate(f,0);b&=-131713;f=M.Ab({node:f,path:M.ua(f),flags:b,seekable:!0,position:0,W:f.W,Pc:[],error:!1});f.W.open&&f.W.open(f);!z.logReadFiles||
b&1||(M.rb||(M.rb={}),a in M.rb||(M.rb[a]=1));return f},close:a=>{if(M.Ja(a))throw new M.T(8);a.ib&&(a.ib=null);try{a.W.close&&a.W.close(a)}catch(b){throw b;}finally{M.cc(a.Ia)}a.Ia=null},Ja:a=>null===a.Ia,ia:(a,b,c)=>{if(M.Ja(a))throw new M.T(8);if(!a.seekable||!a.W.ia)throw new M.T(70);if(0!=c&&1!=c&&2!=c)throw new M.T(28);a.position=a.W.ia(a,b,c);a.Pc=[];return a.position},read:(a,b,c,e,f)=>{if(0>e||0>f)throw new M.T(28);if(M.Ja(a))throw new M.T(8);if(1===(a.flags&2097155))throw new M.T(8);if(M.aa(a.node.mode))throw new M.T(31);
if(!a.W.read)throw new M.T(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new M.T(70);b=a.W.read(a,b,c,e,f);g||(a.position+=b);return b},write:(a,b,c,e,f,g)=>{if(0>e||0>f)throw new M.T(28);if(M.Ja(a))throw new M.T(8);if(0===(a.flags&2097155))throw new M.T(8);if(M.aa(a.node.mode))throw new M.T(31);if(!a.W.write)throw new M.T(28);a.seekable&&a.flags&1024&&M.ia(a,0,2);var k="undefined"!=typeof f;if(!k)f=a.position;else if(!a.seekable)throw new M.T(70);b=a.W.write(a,b,c,
e,f,g);k||(a.position+=b);return b},Ha:(a,b,c)=>{if(M.Ja(a))throw new M.T(8);if(0>b||0>=c)throw new M.T(28);if(0===(a.flags&2097155))throw new M.T(8);if(!M.isFile(a.node.mode)&&!M.aa(a.node.mode))throw new M.T(43);if(!a.W.Ha)throw new M.T(138);a.W.Ha(a,b,c)},Ga:(a,b,c,e,f)=>{if(0!==(e&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new M.T(2);if(1===(a.flags&2097155))throw new M.T(2);if(!a.W.Ga)throw new M.T(43);return a.W.Ga(a,b,c,e,f)},Na:(a,b,c,e,f)=>a.W.Na?a.W.Na(a,b,c,e,f):0,wd:()=>0,lb:(a,b,c)=>
{if(!a.W.lb)throw new M.T(59);return a.W.lb(a,b,c)},Bd:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,e=M.open(a,b.flags);a=M.stat(a).size;var f=new Uint8Array(a);M.read(e,f,0,a,0);"utf8"===b.encoding?c=V(f,0):"binary"===b.encoding&&(c=f);M.close(e);return c},Hd:(a,b,c={})=>{c.flags=c.flags||577;a=M.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(bb(b)+1);b=cb(b,
e,0,e.length);M.write(a,e,0,b,void 0,c.ac)}else if(ArrayBuffer.isView(b))M.write(a,b,0,b.byteLength,void 0,c.ac);else throw Error("Unsupported data type");M.close(a)},Ua:()=>M.Bb,$c:a=>{a=M.Y(a,{ga:!0});if(null===a.node)throw new M.T(44);if(!M.aa(a.node.mode))throw new M.T(54);var b=M.Aa(a.node,"x");if(b)throw new M.T(b);M.Bb=a.path},fc:()=>{M.fa("/tmp");M.fa("/home");M.fa("/home/web_user")},ec:()=>{M.fa("/dev");M.tb(M.ya(1,3),{read:()=>0,write:(e,f,g,k)=>k});M.Za("/dev/null",M.ya(1,3));fb(M.ya(5,
0),hb);fb(M.ya(6,0),ib);M.Za("/dev/tty",M.ya(5,0));M.Za("/dev/tty1",M.ya(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ya(a).byteLength);return a[--b]};M.ra("/dev","random",c);M.ra("/dev","urandom",c);M.fa("/dev/shm");M.fa("/dev/shm/tmp")},ic:()=>{M.fa("/proc");var a=M.fa("/proc/self");M.fa("/proc/self/fd");M.$({$:()=>{var b=M.createNode(a,"fd",16895,73);b.U={xa:(c,e)=>{var f=M.ea(+e);c={parent:null,$:{Nb:"fake"},U:{Ca:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},jc:()=>
{z.stdin?M.ra("/dev","stdin",z.stdin):M.sa("/dev/tty","/dev/stdin");z.stdout?M.ra("/dev","stdout",null,z.stdout):M.sa("/dev/tty","/dev/stdout");z.stderr?M.ra("/dev","stderr",null,z.stderr):M.sa("/dev/tty1","/dev/stderr");M.open("/dev/stdin",0);M.open("/dev/stdout",1);M.open("/dev/stderr",1)},Db:()=>{M.T||(M.T=function(a,b){this.name="ErrnoError";this.node=b;this.Hc=function(c){this.da=c};this.Hc(a);this.message="FS error"},M.T.prototype=Error(),M.T.prototype.constructor=M.T,[44].forEach(a=>{M.hb[a]=
new M.T(a);M.hb[a].stack="<generic error, no stack>"}))},Jc:()=>{M.Db();M.ja=Array(4096);M.$(W,{},"/");M.fc();M.ec();M.ic();M.lc={MEMFS:W}},va:(a,b,c)=>{M.va.kb=!0;M.Db();z.stdin=a||z.stdin;z.stdout=b||z.stdout;z.stderr=c||z.stderr;M.jc()},Ad:()=>{M.va.kb=!1;for(var a=0;a<M.streams.length;a++){var b=M.streams[a];b&&M.close(b)}},kd:(a,b)=>{a=M.Yb(a,b);return a.Eb?a.object:null},Yb:(a,b)=>{try{var c=M.Y(a,{ga:!b});a=c.path}catch(f){}var e={Xa:!1,Eb:!1,error:0,name:null,path:null,object:null,Cc:!1,Ec:null,
Dc:null};try{c=M.Y(a,{parent:!0}),e.Cc=!0,e.Ec=c.path,e.Dc=c.node,e.name=T(a),c=M.Y(a,{ga:!b}),e.Eb=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.Xa="/"===c.path}catch(f){e.error=f.da}return e},cd:(a,b)=>{a="string"==typeof a?a:M.ua(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=S(a+"/"+c);try{M.fa(e)}catch(f){}a=e}}return e},hc:(a,b,c,e,f)=>{a="string"==typeof a?a:M.ua(a);b=S(a+"/"+b);return M.create(b,nb(e,f))},dc:(a,b,c,e,f,g)=>{var k=b;a&&(a="string"==typeof a?a:
M.ua(a),k=b?S(a+"/"+b):a);a=nb(e,f);k=M.create(k,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}M.Ta(k,a|146);b=M.open(k,577);M.write(b,c,0,c.length,0,g);M.close(b);M.Ta(k,a)}return k},ra:(a,b,c,e)=>{a=Wa("string"==typeof a?a:M.ua(a),b);b=nb(!!c,!!e);M.ra.ob||(M.ra.ob=64);var f=M.ya(M.ra.ob++,0);M.tb(f,{open:g=>{g.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(g,k,n,u)=>{for(var m=0,p=0;p<u;p++){try{var y=c()}catch(A){throw new M.T(29);
}if(void 0===y&&0===m)throw new M.T(6);if(null===y||void 0===y)break;m++;k[n+p]=y}m&&(g.node.timestamp=Date.now());return m},write:(g,k,n,u)=>{for(var m=0;m<u;m++)try{e(k[n+m])}catch(p){throw new M.T(29);}u&&(g.node.timestamp=Date.now());return m}});return M.Za(a,b,f)},gb:a=>{if(a.mb||a.wc||a.link||a.V)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");
if(sa)try{a.V=db(sa(a.url),!0),a.Z=a.V.length}catch(b){throw new M.T(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},bd:(a,b,c,e,f)=>{function g(){this.nb=!1;this.ma=[]}g.prototype.get=function(m){if(!(m>this.length-1||0>m)){var p=m%this.zb;return this.Ib(m/this.zb|0)[p]}};g.prototype.Vb=function(m){this.Ib=m};g.prototype.wb=function(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+
". Status: "+m.status);var p=Number(m.getResponseHeader("Content-length")),y,A=(y=m.getResponseHeader("Accept-Ranges"))&&"bytes"===y;m=(y=m.getResponseHeader("Content-Encoding"))&&"gzip"===y;var l=1048576;A||(l=p);var r=this;r.Vb(w=>{var C=w*l,K=(w+1)*l-1;K=Math.min(K,p-1);if("undefined"==typeof r.ma[w]){var fc=r.ma;if(C>K)throw Error("invalid range ("+C+", "+K+") or no bytes requested!");if(K>p-1)throw Error("only "+p+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,
!1);p!==l&&D.setRequestHeader("Range","bytes="+C+"-"+K);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);C=void 0!==D.response?new Uint8Array(D.response||[]):db(D.responseText||"",!0);fc[w]=C}if("undefined"==typeof r.ma[w])throw Error("doXHR failed!");return r.ma[w]});if(m||!p)l=p=1,l=p=this.Ib(0).length,va("LazyFiles on gzip forces download of the whole file when length is accessed");
this.Xb=p;this.Wb=l;this.nb=!0};if("undefined"!=typeof XMLHttpRequest){if(!E)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.nb||this.wb();return this.Xb}},zb:{get:function(){this.nb||this.wb();return this.Wb}}});k={mb:!1,V:k}}else k={mb:!1,url:c};var n=M.hc(a,b,k,e,f);k.V?n.V=k.V:k.url&&(n.V=null,n.url=k.url);Object.defineProperties(n,{Z:{get:function(){return this.V.length}}});
var u={};Object.keys(n.W).forEach(m=>{var p=n.W[m];u[m]=function(){M.gb(n);return p.apply(null,arguments)}});u.read=(m,p,y,A,l)=>{M.gb(n);m=m.node.V;if(l>=m.length)p=0;else{A=Math.min(m.length-l,A);if(m.slice)for(var r=0;r<A;r++)p[y+r]=m[l+r];else for(r=0;r<A;r++)p[y+r]=m.get(l+r);p=A}return p};u.Ga=()=>{M.gb(n);J();throw new M.T(48);};n.W=u;return n}},ob=a=>(a>>>=0)?V(aa(),a):"",X=void 0;function Y(){X+=4;return v()[X-4>>2>>>0]}
function pb(a){if(F)return Z(1,1,a);L=a;if(!Fa()){B.Qb();if(z.onExit)z.onExit(a);xa=!0}oa(a,new Qa(a))}
var rb=a=>{L=a;if(F)throw qb(a),"unwind";pb(a)},sb=a=>{a instanceof Qa||"unwind"==a||oa(1,a)},B={ta:[],Da:[],Sb:[],qa:{},va:function(){F?B.qc():B.pc()},pc:function(){for(var a=32;a--;)B.vb();Aa.unshift(()=>{Ja();B.xc(()=>P())})},qc:function(){B.receiveObjectTransfer=B.Fc;B.threadInitTLS=B.Rb;B.setExitStatus=B.Ob;noExitRuntime=!1},Ob:function(a){L=a},Dd:["$terminateWorker"],Qb:function(){for(var a of B.Da)Ra(a);for(a of B.ta)Ra(a);B.ta=[];B.Da=[];B.qa=[]},Gc:function(a){var b=a.Ba;delete B.qa[b];B.ta.push(a);
B.Da.splice(B.Da.indexOf(a),1);a.Ba=0;tb(b)},Fc:function(){},Rb:function(){B.Sb.forEach(a=>a())},Mb:a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var k=g.cmd;if(g.targetThread&&g.targetThread!=ub()){var n=B.qa[g.Cd];n?n.postMessage(g,g.transferList):H('Internal error! Worker sent a message "'+k+'" to target pthread '+g.targetThread+", but that thread no longer exists!")}else if("checkMailbox"===k)vb();else if("spawnThread"===k)Ta(g);else if("cleanupThread"===k)Sa(g.thread);else if("killThread"===k)g=
g.thread,k=B.qa[g],delete B.qa[g],Ra(k),tb(g),B.Da.splice(B.Da.indexOf(k),1),k.Ba=0;else if("cancelThread"===k)B.qa[g.thread].postMessage({cmd:"cancel"});else if("loaded"===k)a.loaded=!0,b(a);else if("alert"===k)alert("Thread "+g.threadId+": "+g.text);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===k)z[g.handler](...g.args);else k&&H("worker sent an unknown command "+k)};a.onerror=g=>{H("worker sent an error! "+g.filename+":"+g.lineno+": "+g.message);throw g;};var c=[],
e=["onExit","onAbort","print","printErr"],f;for(f of e)z.hasOwnProperty(f)&&c.push(f);a.postMessage({cmd:"load",handlers:c,urlOrBlob:z.mainScriptUrlOrBlob,wasmMemory:h,wasmModule:wa})}),xc:function(a){if(F)return a();Promise.all(B.ta.map(B.Mb)).then(a)},vb:function(){if(z.locateFile){var a=ra("yaneuraou.k-p.worker.js");a=new Worker(a)}else a=new Worker(new URL("yaneuraou.k-p.worker.js",import.meta.url));B.ta.push(a)},nc:function(){0==B.ta.length&&(B.vb(),B.Mb(B.ta[0]));return B.ta.pop()}};
z.PThread=B;var Ha=a=>{for(;0<a.length;)a.shift()(z)};z.establishStackSpace=function(){var a=ub(),b=v()[a+52>>2>>>0];a=v()[a+56>>2>>>0];wb(b,b-a);xb(b)};function qb(a){if(F)return Z(2,0,a);rb(a)}var yb=[];z.invokeEntryPoint=function(a,b){var c=yb[a];c||(a>=yb.length&&(yb.length=a+1),yb[a]=c=za.get(a));a=c(b);Fa()?B.Ob(a):zb(a)};function Ab(a,b,c,e){return F?Z(3,1,a,b,c,e):Bb(a,b,c,e)}
function Bb(a,b,c,e){a>>>=0;b>>>=0;c>>>=0;e>>>=0;if("undefined"==typeof SharedArrayBuffer)return H("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(F&&0===f.length)return Ab(a,b,c,e);a={Ic:c,Ba:a,Zb:e,Oc:f};return F?(a.ad="spawnThread",postMessage(a,f),0):Ta(a)}
function Cb(a,b,c){if(F)return Z(4,1,a,b,c);X=c>>>0;try{var e=M.ea(a);switch(b){case 0:var f=Y();return 0>f?-28:M.Ab(e,f).Ia;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=Y(),e.flags|=f,0;case 5:return f=Y(),ca()[f+0>>1>>>0]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return v()[Db()>>2>>>0]=28,-1;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.da}}
function Eb(a,b){if(F)return Z(5,1,a,b);b>>>=0;try{if(0===b)return-28;var c=M.Ua(),e=bb(c)+1;if(b<e)return-68;a>>>=0;cb(c,aa(),a,b);return e}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.da}}
function Fb(a,b,c){if(F)return Z(6,1,a,b,c);X=c>>>0;try{var e=M.ea(a);switch(b){case 21509:return e.X?0:-59;case 21505:if(!e.X)return-59;if(e.X.pa.rc){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=Y();v()[f>>2>>>0]=25856;v()[f+4>>2>>>0]=5;v()[f+8>>2>>>0]=191;v()[f+12>>2>>>0]=35387;for(var g=0;32>g;g++)d()[f+g+17>>0>>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return e.X?0:-59;case 21506:case 21507:case 21508:if(!e.X)return-59;if(e.X.pa.sc)for(f=Y(),
v(),v(),v(),v(),a=[],g=0;32>g;g++)a.push(d()[f+g+17>>0>>>0]);return 0;case 21519:if(!e.X)return-59;f=Y();return v()[f>>2>>>0]=0;case 21520:return e.X?-28:-59;case 21531:return f=Y(),M.lb(e,b,f);case 21523:if(!e.X)return-59;e.X.pa.tc&&(g=[24,80],f=Y(),ca()[f>>1>>>0]=g[0],ca()[f+2>>1>>>0]=g[1]);return 0;case 21524:return e.X?0:-59;case 21515:return e.X?0:-59;default:return-28}}catch(k){if("undefined"==typeof M||"ErrnoError"!==k.name)throw k;return-k.da}}
function Gb(a,b,c,e){if(F)return Z(7,1,a,b,c,e);b>>>=0;X=e>>>=0;try{b=ob(b);var f=b;if("/"===f.charAt(0))b=f;else{var g=-100===a?M.Ua():M.ea(a).path;if(0==f.length)throw new M.T(44);b=S(g+"/"+f)}var k=e?Y():0;return M.open(b,c,k).Ia}catch(n){if("undefined"==typeof M||"ErrnoError"!==n.name)throw n;return-n.da}}var Hb=a=>{if(!xa)try{if(a(),!Fa())try{F?zb(L):rb(L)}catch(b){sb(b)}}catch(b){sb(b)}};
function Ib(a){a>>>=0;"function"===typeof Atomics.Rc&&(Atomics.Rc(v(),a>>2,a).value.then(vb),a+=128,Atomics.store(v(),a>>2,1))}z.__emscripten_thread_mailbox_await=Ib;function vb(){var a=ub();a&&(Ib(a),Hb(()=>Jb()))}z.checkMailbox=vb;var Lb=a=>{var b=Kb();a=a();xb(b);return a};function Z(a,b){var c=arguments.length-2,e=arguments;return Lb(()=>{for(var f=Mb(8*c),g=f>>3,k=0;k<c;k++){var n=e[2+k];ha()[g+k>>>0]=n}return Nb(a,c,f,b)})}
var Ob=[],Pb={},Rb=()=>{if(!Qb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in Pb)void 0===Pb[b]?delete a[b]:a[b]=Pb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qb=c}return Qb},Qb;
function Sb(a,b){if(F)return Z(8,1,a,b);a>>>=0;b>>>=0;var c=0;Rb().forEach(function(e,f){var g=b+c;f=x()[a+4*f>>2>>>0]=g;for(g=0;g<e.length;++g)d()[f++>>0>>>0]=e.charCodeAt(g);d()[f>>0>>>0]=0;c+=e.length+1});return 0}function Tb(a,b){if(F)return Z(9,1,a,b);a>>>=0;b>>>=0;var c=Rb();x()[a>>2>>>0]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});x()[b>>2>>>0]=e;return 0}
function Ub(a){if(F)return Z(10,1,a);try{var b=M.ea(a);M.close(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.da}}
function Vb(a,b,c,e){if(F)return Z(11,1,a,b,c,e);b>>>=0;c>>>=0;e>>>=0;try{a:{var f=M.ea(a);a=b;for(var g,k=b=0;k<c;k++){var n=x()[a>>2>>>0],u=x()[a+4>>2>>>0];a+=8;var m=M.read(f,d(),n,u,g);if(0>m){var p=-1;break a}b+=m;if(m<u)break;"undefined"!==typeof g&&(g+=m)}p=b}x()[e>>2>>>0]=p;return 0}catch(y){if("undefined"==typeof M||"ErrnoError"!==y.name)throw y;return y.da}}
function Wb(a,b,c,e,f){if(F)return Z(12,1,a,b,c,e,f);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;f>>>=0;try{if(isNaN(b))return 61;var g=M.ea(a);M.ia(g,b,e);Pa=[g.position>>>0,(R=g.position,1<=+Math.abs(R)?0<R?+Math.floor(R/4294967296)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];v()[f>>2>>>0]=Pa[0];v()[f+4>>2>>>0]=Pa[1];g.ib&&0===b&&0===e&&(g.ib=null);return 0}catch(k){if("undefined"==typeof M||"ErrnoError"!==k.name)throw k;return k.da}}
function Xb(a,b,c,e){if(F)return Z(13,1,a,b,c,e);b>>>=0;c>>>=0;e>>>=0;try{a:{var f=M.ea(a);a=b;for(var g,k=b=0;k<c;k++){var n=x()[a>>2>>>0],u=x()[a+4>>2>>>0];a+=8;var m=M.write(f,d(),n,u,g);if(0>m){var p=-1;break a}b+=m;"undefined"!==typeof g&&(g+=m)}p=b}x()[e>>2>>>0]=p;return 0}catch(y){if("undefined"==typeof M||"ErrnoError"!==y.name)throw y;return y.da}}
var Yb=a=>0===a%4&&(0!==a%100||0===a%400),Zb=[31,29,31,30,31,30,31,31,30,31,30,31],$b=[31,28,31,30,31,30,31,31,30,31,30,31],ac=(a,b)=>{d().set(a,b>>>0)};
function bc(a,b,c,e){function f(l,r,w){for(l="number"==typeof l?l.toString():l||"";l.length<r;)l=w[0]+l;return l}function g(l,r){return f(l,r,"0")}function k(l,r){function w(K){return 0>K?-1:0<K?1:0}var C;0===(C=w(l.getFullYear()-r.getFullYear()))&&0===(C=w(l.getMonth()-r.getMonth()))&&(C=w(l.getDate()-r.getDate()));return C}function n(l){switch(l.getDay()){case 0:return new Date(l.getFullYear()-1,11,29);case 1:return l;case 2:return new Date(l.getFullYear(),0,3);case 3:return new Date(l.getFullYear(),
0,2);case 4:return new Date(l.getFullYear(),0,1);case 5:return new Date(l.getFullYear()-1,11,31);case 6:return new Date(l.getFullYear()-1,11,30)}}function u(l){var r=l.Ea;for(l=new Date((new Date(l.Fa+1900,0,1)).getTime());0<r;){var w=l.getMonth(),C=(Yb(l.getFullYear())?Zb:$b)[w];if(r>C-l.getDate())r-=C-l.getDate()+1,l.setDate(1),11>w?l.setMonth(w+1):(l.setMonth(0),l.setFullYear(l.getFullYear()+1));else{l.setDate(l.getDate()+r);break}}w=new Date(l.getFullYear()+1,0,4);r=n(new Date(l.getFullYear(),
0,4));w=n(w);return 0>=k(r,l)?0>=k(w,l)?l.getFullYear()+1:l.getFullYear():l.getFullYear()-1}a>>>=0;b>>>=0;c>>>=0;e>>>=0;var m=v()[e+40>>2>>>0];e={Mc:v()[e>>2>>>0],Lc:v()[e+4>>2>>>0],bb:v()[e+8>>2>>>0],ub:v()[e+12>>2>>>0],cb:v()[e+16>>2>>>0],Fa:v()[e+20>>2>>>0],la:v()[e+24>>2>>>0],Ea:v()[e+28>>2>>>0],Ed:v()[e+32>>2>>>0],Kc:v()[e+36>>2>>>0],Nc:m?ob(m):""};c=ob(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y",
"%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");m={"%a":l=>y[l.la].substring(0,3),"%A":l=>
y[l.la],"%b":l=>A[l.cb].substring(0,3),"%B":l=>A[l.cb],"%C":l=>g((l.Fa+1900)/100|0,2),"%d":l=>g(l.ub,2),"%e":l=>f(l.ub,2," "),"%g":l=>u(l).toString().substring(2),"%G":l=>u(l),"%H":l=>g(l.bb,2),"%I":l=>{l=l.bb;0==l?l=12:12<l&&(l-=12);return g(l,2)},"%j":l=>{for(var r=0,w=0;w<=l.cb-1;r+=(Yb(l.Fa+1900)?Zb:$b)[w++]);return g(l.ub+r,3)},"%m":l=>g(l.cb+1,2),"%M":l=>g(l.Lc,2),"%n":()=>"\n","%p":l=>0<=l.bb&&12>l.bb?"AM":"PM","%S":l=>g(l.Mc,2),"%t":()=>"\t","%u":l=>l.la||7,"%U":l=>g(Math.floor((l.Ea+7-l.la)/
7),2),"%V":l=>{var r=Math.floor((l.Ea+7-(l.la+6)%7)/7);2>=(l.la+371-l.Ea-2)%7&&r++;if(r)53==r&&(w=(l.la+371-l.Ea)%7,4==w||3==w&&Yb(l.Fa)||(r=1));else{r=52;var w=(l.la+7-l.Ea-1)%7;(4==w||5==w&&Yb(l.Fa%400-1))&&r++}return g(r,2)},"%w":l=>l.la,"%W":l=>g(Math.floor((l.Ea+7-(l.la+6)%7)/7),2),"%y":l=>(l.Fa+1900).toString().substring(2),"%Y":l=>l.Fa+1900,"%z":l=>{l=l.Kc;var r=0<=l;l=Math.abs(l)/60;return(r?"+":"-")+String("0000"+(l/60*100+l%60)).slice(-4)},"%Z":l=>l.Nc,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");
for(p in m)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),m[p](e)));c=c.replace(/\0\0/g,"%");p=db(c,!1);if(p.length>b)return 0;ac(p,a);return p.length-1}var cc=a=>{var b=bb(a)+1,c=Mb(b);cb(a,aa(),c,b);return c};B.va();function dc(a,b,c,e){a||(a=this);this.parent=a;this.$=a.$;this.La=null;this.id=M.Ac++;this.name=b;this.mode=c;this.U={};this.W={};this.$a=e}
Object.defineProperties(dc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},wc:{get:function(){return M.aa(this.mode)}},mb:{get:function(){return M.Wa(this.mode)}}});M.Tb=dc;
M.dd=function(a,b,c,e,f,g,k,n,u,m){function p(A){function l(r){m&&m();n||M.dc(a,b,r,e,f,u);g&&g();P()}mb(A,y,l,()=>{k&&k();P()})||l(A)}var y=b?U(S(a+"/"+b)):a;Ja();"string"==typeof c?kb(c,A=>p(A),k):p(c)};M.Jc();
var ec=[null,pb,qb,Ab,Cb,Eb,Fb,Gb,Sb,Tb,Ub,Vb,Wb,Xb],hc={x:function(a){gc(a>>>0,!E,1,!pa,67108864);B.Rb()},f:function(a){a>>>=0;F?postMessage({cmd:"cleanupThread",thread:a}):Sa(a)},t:Bb,e:Cb,y:Eb,B:Fb,i:Gb,l:()=>!0,s:function(a,b){a>>>=0;a==b>>>0?setTimeout(()=>vb()):F?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=B.qa[a])&&a.postMessage({cmd:"checkMailbox"})},v:function(){return-1},w:Ib,k:function(){},b:()=>{J("")},h:function(){},m:function(){return Date.now()},j:()=>{Ea+=1;throw"unwind";},
c:()=>performance.timeOrigin+performance.now(),u:function(a,b,c,e){B.fd=b>>>0;Ob.length=c;b=e>>>0>>3;for(e=0;e<c;e++)Ob[e]=ha()[b+e>>>0];return ec[a].apply(null,Ob)},r:function(a){a>>>=0;var b=aa().length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=f.min.call(f,4294901760,e+(65536-e%65536)%65536)-h.buffer.byteLength+65535>>>16;try{h.grow(f);t();var g=1;break a}catch(k){}g=void 0}if(g)return!0}return!1},p:Sb,q:Tb,
d:rb,g:Ub,A:Vb,n:Wb,z:Xb,a:h||z.wasmMemory,o:function(a,b,c,e){return bc(a>>>0,b>>>0,c>>>0,e>>>0)}};(function(){function a(c,e){c=c.exports;c=ic(c);z.asm=c;B.Sb.push(z.asm.F);za=z.asm.J;Ba.unshift(z.asm.C);wa=e;P();return c}var b={a:hc};Ja();if(z.instantiateWasm)try{return z.instantiateWasm(b,a)}catch(c){H("Module.instantiateWasm callback failed with error: "+c),ka(c)}Oa(b,function(c){a(c.instance,c.module)}).catch(ka);return{}})();var jc=z._main=function(){return(jc=z._main=z.asm.D).apply(null,arguments)};
z._usi_command=function(){return(z._usi_command=z.asm.E).apply(null,arguments)};z.__emscripten_tls_init=function(){return(z.__emscripten_tls_init=z.asm.F).apply(null,arguments)};var ub=z._pthread_self=function(){return(ub=z._pthread_self=z.asm.G).apply(null,arguments)};function Db(){return(Db=z.asm.H).apply(null,arguments)}var gc=z.__emscripten_thread_init=function(){return(gc=z.__emscripten_thread_init=z.asm.I).apply(null,arguments)};
z.__emscripten_thread_crashed=function(){return(z.__emscripten_thread_crashed=z.asm.K).apply(null,arguments)};function Nb(){return(Nb=z.asm.L).apply(null,arguments)}function tb(){return(tb=z.asm.M).apply(null,arguments)}var zb=z.__emscripten_thread_exit=function(){return(zb=z.__emscripten_thread_exit=z.asm.N).apply(null,arguments)},Jb=z.__emscripten_check_mailbox=function(){return(Jb=z.__emscripten_check_mailbox=z.asm.O).apply(null,arguments)};
function wb(){return(wb=z.asm.P).apply(null,arguments)}function Kb(){return(Kb=z.asm.Q).apply(null,arguments)}function xb(){return(xb=z.asm.R).apply(null,arguments)}function Mb(){return(Mb=z.asm.S).apply(null,arguments)}function ic(a){a=Object.assign({},a);var b=e=>()=>e()>>>0,c=e=>f=>e(f)>>>0;a.pthread_self=b(a.pthread_self);a.__errno_location=b(a.__errno_location);a.malloc=c(a.malloc);a.stackSave=b(a.stackSave);a.stackAlloc=c(a.stackAlloc);return a}z.keepRuntimeAlive=Fa;z.wasmMemory=h;
z.ccall=function(a,b,c,e){var f={string:m=>{var p=0;null!==m&&void 0!==m&&0!==m&&(p=cc(m));return p},array:m=>{var p=Mb(m.length);d().set(m,p>>>0);return p}};a=z["_"+a];var g=[],k=0;if(e)for(var n=0;n<e.length;n++){var u=f[c[n]];u?(0===k&&(k=Kb()),g[n]=u(e[n])):g[n]=e[n]}c=a.apply(null,g);return c=function(m){0!==k&&xb(k);return"string"===b?ob(m):"boolean"===b?!!m:m}(c)};z.ExitStatus=Qa;z.FS=M;z.PThread=B;var kc;O=function lc(){kc||mc();kc||(O=lc)};
function nc(a=[]){var b=jc;a.unshift(na);var c=a.length,e=Mb(4*(c+1)),f=e>>2;a.forEach(k=>{v()[f++>>>0]=cc(k)});v()[f>>>0]=0;try{var g=b(c,e);rb(g,!0)}catch(k){sb(k)}}
function mc(){var a=ma;function b(){if(!kc&&(kc=!0,z.calledRun=!0,!xa)){Ga();F||Ha(Ca);ja(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();oc&&nc(a);if(!F){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var c=z.postRun.shift();Da.unshift(c)}Ha(Da)}}}if(!(0<N))if(F)ja(z),Ga(),startWorker(z);else{if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Aa.unshift(z.preRun.shift());Ha(Aa);0<N||(z.setStatus?(z.setStatus("Running..."),
setTimeout(function(){setTimeout(function(){z.setStatus("")},1);b()},1)):b())}}if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();var oc=!0;z.noInitialRun&&(oc=!1);mc();


  return moduleArg.ready
}

);
})();
export default YaneuraOu_K_P;